spring:
  profiles.active: default
---
server:
        port: 9090
spring:
    application:
        name: TEST
eureka:
    password: password
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@192.168.99.100:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}



---
spring:
  profiles: docker
eureka:
    password: password
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@eureka:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
