spring:
  profiles.active: default
---
server:
    port: 8181
spring:
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: create-drop
        show-sql: true


    datasource:
        url: jdbc:postgresql://192.168.1.16:5432/demo
        username: postgres
        password: mysecretpassword
        driver-class-name: org.postgresql.Driver
RESTConfiguration:
    broadcast:
        account:
            path: "/accountBr"
---
spring:
  profiles: docker
spring.datasource:
  url: jdbc:postgresql://192.168.1.16:5432/demo