spring:
  profiles.active: default
---
spring:
    application:
        name: Order
    server:
        port: 8080
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    datasource:
        url: jdbc:mysql://192.168.1.16:3306/demo
        username: demo_user
        password: demo_pass
        driver-class-name: com.mysql.jdbc.Driver

eureka:
    password: password
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@192.168.1.16:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

RESTConfiguration:
    broadcast:
        account:
            message: "/accountMsg"
            sendPath: "/accountBr"
    view:
        item:
            path: "/Item"
            one:
                path: "/one"
            all:
                path: "/all"
                favorite:
                    path: "/Favorite"
        account:
            path: "/Account"
            one:
                path: "/one"
                mail:
                    path: "/mail"
                name:
                    path: "/name"
            all:
                path: "/all"
        favorite:
            path: "/Favorite"
            one:
                path: "/one"
                order:
                    path: "/Order"
            all:
                path: "/all"
                account:
                    path: "/Account"
        order:
            path: "/Order"
            one:
                path: "/one"
            all:
                path: "/all"
                account:
                    path: "/Account"
---
spring.profiles: docker
spring.datasource:
  url: jdbc:mysql://mysql:3306/demo

eureka:
    password: password
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@eureka:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
