spring:
  profiles.active: default
---
server:
    port: 8700
spring:
    application:
        name: CookBook
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    datasource:
        url: jdbc:postgresql://192.168.99.100:8701/demo
        username: postgres
        password: mysecretpassword
        driver-class-name: org.postgresql.Driver
eureka:
    password: password
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@192.168.99.100:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

---
spring:
  profiles: docker
spring.datasource:
  url: jdbc:postgresql://some-postgres:8701/demo
eureka:
    password: password
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@eureka:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
