version: '2.1'
services:
  db:
    container_name: db
    image: mongo:3.0
    ports:
      - 27017:27017
    command: --smallfiles

  rocketchat:
    container_name: rocketchat
    build: ./../rocket.chat
    ports:
        - 3000:3000
        - 9090:9090
    depends_on:
        - db
    links:
        - db:db
